export const GET_VOTES_FAIL =
  'GET_VOTES_FAIL';
export const GET_VOTES_PENDING =
  'GET_VOTES_PENDING';
export const GET_VOTES_SUCCESS =
  'GET_VOTES_SUCCESS';

export const SUBMIT_VOTE_FAIL =
  'SUBMIT_VOTE_FAIL';
export const SUBMIT_VOTE_PENDING =
  'SUBMIT_VOTE_PENDING';
export const SUBMIT_VOTE_SUCCESS =
  'SUBMIT_VOTE_SUCCESS';
