export const DELETE_POLL_FAIL =
  'DELETE_POLL_FAIL';
export const DELETE_POLL_PENDING =
  'DELETE_POLL_PENDING';
export const DELETE_POLL_SUCCESS =
  'DELETE_POLL_SUCCESS';

export const GET_POLLS_FAIL =
  'GET_POLLS_FAIL';
export const GET_POLLS_PENDING =
  'GET_POLLS_PENDING';
export const GET_POLLS_SUCCESS =
  'GET_POLLS_SUCCESS';

export const SHARE_POLL = 'SHARE_POLL';

export const SUBMIT_POLL_FAIL =
  'SUBMIT_POLL_FAIL';
export const SUBMIT_POLL_PENDING =
  'SUBMIT_POLL_PENDING';
export const SUBMIT_POLL_SUCCESS =
  'SUBMIT_POLL_SUCCESS';

export const SUBMIT_REASON_FAIL =
  'SUBMIT_REASON_FAIL';
export const SUBMIT_REASON_PENDING =
  'SUBMIT_REASON_PENDING';
export const SUBMIT_REASON_SUCCESS =
  'SUBMIT_REASON_SUCCESS';
