export const SIGN_IN_FACEBOOK_FAIL = 'SIGN_IN_FACEBOOK_FAIL';
export const SIGN_IN_FACEBOOK_SUCCESS = 'SIGN_IN_FACEBOOK_SUCCESS';

export const SIGN_OUT_FACEBOOK_FAIL = 'SIGN_OUT_FACEBOOK_FAIL';
export const SIGN_OUT_FACEBOOK_SUCCESS = 'SIGN_OUT_FACEBOOK_SUCCESS';
