// getUserIP.js
export const GET_USER_IP_FAIL =
  'GET_USER_IP_FAIL';
export const GET_USER_IP_PENDING =
  'GET_USER_IP_PENDING';
export const GET_USER_IP_SUCCESS =
  'GET_USER_IP_SUCCESS';

// signInFacebook.js
export const SIGN_IN_FACEBOOK_FAIL =
  'SIGN_IN_FACEBOOK_FAIL';
export const SIGN_IN_FACEBOOK_PENDING =
  'SIGN_IN_FACEBOOK_PENDING';
export const SIGN_IN_FACEBOOK_SUCCESS =
  'SIGN_IN_FACEBOOK_SUCCESS';

// signOutFacebook.js
export const SIGN_OUT_FACEBOOK_FAIL =
  'SIGN_OUT_FACEBOOK_FAIL';
export const SIGN_OUT_FACEBOOK_PENDING =
  'SIGN_OUT_FACEBOOK_PENDING';
export const SIGN_OUT_FACEBOOK_SUCCESS =
  'SIGN_OUT_FACEBOOK_SUCCESS';
