// getFirebaseUser.js
export const GET_FIREBASE_USER_FAIL = 'GET_FIREBASE_USER_FAIL';
export const GET_FIREBASE_USER_PENDING = 'GET_FIREBASE_USER_PENDING';
export const GET_FIREBASE_USER_SUCCESS = 'GET_FIREBASE_USER_SUCCESS';

// updateFirebaseUser.js
export const UPDATE_FIREBASE_USER_FAIL = 'UPDATE_FIREBASE_USER_FAIL';
export const UPDATE_FIREBASE_USER_PENDING = 'UPDATE_FIREBASE_USER_PENDING';
export const UPDATE_FIREBASE_USER_SUCCESS = 'UPDATE_FIREBASE_USER_SUCCESS';
