// getFirebaseUser.js
export const GET_FIREBASE_USER_FAIL =
  'GET_FIREBASE_USER_FAIL';
export const GET_FIREBASE_USER_PENDING =
  'GET_FIREBASE_USER_PENDING';
export const GET_FIREBASE_USER_SUCCESS =
  'GET_FIREBASE_USER_SUCCESS';
